In [41]:
# <Save_C3DFeatures_32Segments.m> -> python file


#-*- encoding: utf8 -*-
import os
import numpy as np
import struct

    ## <read_featureFC_file.py>(from 도롱빈)================================
def read_bin(input_file):
# input_file = open(r'.\normal_video_001\000032.fc6-1','rb')
    input_file = open(input_file,'rb')
    try:
        sizes = [struct.unpack('i',input_file.read(4))[0] for i in range(5)]
        m = np.prod(sizes)
        data = [struct.unpack('f',input_file.read(4))[0] for i in range(m)]
    finally:
        input_file
    feature_vector = np.array(data)

    return feature_vector, feature_vector.shape

    ## ======================================================================

C3D_Path = r'/content/drive/My Drive/warming-up project/c3d_ex/abnormal_video_fc'
C3D_Path_Seg = r'/content/drive/My Drive/warming-up project/c3d_ex/output_abnormal_final_c3d'


All_Folder = os.listdir(C3D_Path)
subcript = '_C.txt'

for ifolder in All_Folder:
    print(ifolder)
    # START 1 LOOP WITH 1 FC FOLDER(영상 1개)

    Folder_Path = str(C3D_Path) + "/" + str(ifolder)
    AllFiles = os.listdir(Folder_Path) # /.fc6-1 확장자 파일 싹다 리스트로 반환
                                       # fc6-1 files in feature directory, each file = a clip in video
                                       # one clip = 16 frames

    if len(AllFiles) == 0:
        print("no fc6-1 file in path")
        continue
    
    # .fc6-1 읽고 feature_vector 생성
    feature_vector = np.zeros((len(AllFiles), 4096))
    # each fc6-1 = 1 clips 16 frames = 4096-d ==> Total is [N/16]=88 clips like that
    # Iterate each fc6-1 file (16 frames each)
    for ifile in range(0,len(AllFiles)):
        FilePath =Folder_Path + '/' + AllFiles[ifile]

        data, s = read_bin(FilePath)
        feature_vector[ifile]=data # 1 row 4096-d in 88x4096 is assign by 1 clip feature (4096) ???????????? column을 row로 바꿈

    # 이제 fc6-1을 모두 읽어서 feature_vector(shape = (fc6-1 files 개수) x 4096)에 넣음


#----------------------------------------------------------------------------------
# 여기서부터 feature vector를 32seg로 나눔
# ((fc6-1 files 개수), 4096) -> (32, 4096)으로 만들어서 새로운 파일로 저장
# 여기서 만든 파일을 Training_AnomalyDetector_public.py에 넣어서 training 시킬 수 있음

    txt_file_name = C3D_Path_Seg + '/' + ifolder +subcript
    # feature txt name i.e abnormal_video_001_C.txt

    # fid1 = open(txt_file_name, 'w')

    sum_row = np.sum(feature_vector, axis=1) # 각 16 frame clip에 해당하는 row를 sum
    if np.where(sum_row==0)[0].size != 0:
        print('Error2')
    if np.isnan(feature_vector).sum() != 0:
        print('Error3')
    if np.inf in feature_vector:
        print('Error4')
 

    # 32 Segments
    Segments_Features = np.zeros((32, 4096))    # (32, 4096)
    thirty2_shots = np.linspace(0, len(AllFiles)-1, 33).astype(int) # AllFiles = .fc-1 확장자 파일들 ?????함수 안의 값 변경
    # SO: thirty2shots = [1 , 4, 6, 10, ..... 83, 85, 88], total elements is 33, vector 1x33
    
    count = -1
    # WRITE (88, 4096) TO (32, 4096)
    for ishots in range(0,len(thirty2_shots) - 1):  # ishorts starts from 0 to 31 (총 32개)
        ss = int(thirty2_shots[ishots])            # start clip index 
        ee = int(thirty2_shots[ishots + 1] - 1)     # end clip index 
        

        if ss == ee: # thirty2_shots에서 값의 차이가 1일 때
            temp_vect = feature_vector[ss] # ss==ee --> get 1 vector 4096-d from 88x4096

        elif ee < ss: # 영상 frame이 적어서 thirty2_shots에 같은 숫자가 나오는 경우
            temp_vect = feature_vector[ss]  # get 1 vector 4096-d from 88x4096

        else:
            temp_vect = feature_vector[ss:ee].mean(axis=0) # 각 열의 평균값을 가진 (1, 4096) 추출
                                                           # multiple rows vector -> one row vector

        # NORM-2 (L2)
        temp_vect = np.round(temp_vect / np.linalg.norm(temp_vect), 6)
        # divide by norm-2 (L2) of vector (Euclidean norm)=cumsum(sqrt(x[i]^2))

        if np.linalg.norm(temp_vect) == 0:
            print('Error5')

        count = count + 1 # next segment (max=32)
        Segments_Features[count]= temp_vect # push each segment feature to final 32 video segments feature



    # save 32 segment features in text file ( You can directly save and load .mat file in python as well).
    print(Segments_Features)
    # print(Segments_Features.shape)

    # for i in range(0,Segments_Features.shape[0]):
    #     feat_text = str(Segments_Features[i].tolist())
    #     fid1.write(feat_text)
    #     fid1.write('\n')
    np.savetxt(txt_file_name, Segments_Features, fmt="%.6f")

    # fid1.close()



abnormal_video_001
[[0.       0.       0.027733 ... 0.       0.       0.      ]
 [0.       0.       0.014779 ... 0.       0.       0.030944]
 [0.       0.       0.002643 ... 0.       0.       0.006323]
 ...
 [0.       0.       0.       ... 0.       0.       0.      ]
 [0.       0.       0.       ... 0.       0.       0.023944]
 [0.       0.       0.       ... 0.       0.       0.002591]]


In [34]:
import pandas as pd
ex1 = pd.read_csv('/content/drive/My Drive/warming-up project/c3d_ex/output_abnormal_final_c3d/abnormal_video_001_C.txt', delimiter=' ', header=None)
ex1

0     1         2     3         4     ...  4091  4092  4093  4094      4095
0    0.0   0.0  0.027733   0.0  0.027292  ...   0.0   0.0   0.0   0.0  0.000000
1    0.0   0.0  0.014779   0.0  0.029923  ...   0.0   0.0   0.0   0.0  0.030944
2    0.0   0.0  0.002643   0.0  0.019655  ...   0.0   0.0   0.0   0.0  0.006323
3    0.0   0.0  0.003924   0.0  0.051197  ...   0.0   0.0   0.0   0.0  0.000000
4    0.0   0.0  0.000000   0.0  0.035355  ...   0.0   0.0   0.0   0.0  0.000000
5    0.0   0.0  0.003340   0.0  0.049466  ...   0.0   0.0   0.0   0.0  0.000000
6    0.0   0.0  0.003474   0.0  0.025266  ...   0.0   0.0   0.0   0.0  0.000000
7    0.0   0.0  0.000000   0.0  0.031401  ...   0.0   0.0   0.0   0.0  0.000000
8    0.0   0.0  0.006588   0.0  0.029993  ...   0.0   0.0   0.0   0.0  0.000000
9    0.0   0.0  0.000000   0.0  0.027312  ...   0.0   0.0   0.0   0.0  0.018452
10   0.0   0.0  0.012842   0.0  0.041923  ...   0.0   0.0   0.0   0.0  0.000000
11   0.0   0.0  0.006950   0.0  0.039839  ...   0.0   0.0   0.0   0.0  0.012303
12   0.0   0.0  0.008834   0.0  0.019214  ...   0.0   0.0   0.0   0.0  0.017517
13   0.0   0.0  0.000000   0.0  0.044852  ...   0.0   0.0   0.0   0.0  0.000000
14   0.0   0.0  0.010935   0.0  0.037024  ...   0.0   0.0   0.0   0.0  0.012875
15   0.0   0.0  0.000000   0.0  0.044472  ...   0.0   0.0   0.0   0.0  0.000000
16   0.0   0.0  0.039695   0.0  0.037838  ...   0.0   0.0   0.0   0.0  0.010592
17   0.0   0.0  0.018564   0.0  0.026982  ...   0.0   0.0   0.0   0.0  0.000000
18   0.0   0.0  0.032732   0.0  0.041210  ...   0.0   0.0   0.0   0.0  0.014958
19   0.0   0.0  0.000000   0.0  0.036324  ...   0.0   0.0   0.0   0.0  0.000000
20   0.0   0.0  0.000000   0.0  0.040302  ...   0.0   0.0   0.0   0.0  0.006401
21   0.0   0.0  0.000000   0.0  0.030916  ...   0.0   0.0   0.0   0.0  0.000000
22   0.0   0.0  0.000000   0.0  0.025442  ...   0.0   0.0   0.0   0.0  0.000000
23   0.0   0.0  0.000000   0.0  0.027464  ...   0.0   0.0   0.0   0.0  0.000000
24   0.0   0.0  0.025003   0.0  0.050160  ...   0.0   0.0   0.0   0.0  0.026311
25   0.0   0.0  0.000000   0.0  0.033135  ...   0.0   0.0   0.0   0.0  0.000000
26   0.0   0.0  0.000000   0.0  0.034255  ...   0.0   0.0   0.0   0.0  0.000000
27   0.0   0.0  0.017607   0.0  0.030381  ...   0.0   0.0   0.0   0.0  0.013509
28   0.0   0.0  0.012072   0.0  0.055158  ...   0.0   0.0   0.0   0.0  0.000000
29   0.0   0.0  0.000000   0.0  0.049065  ...   0.0   0.0   0.0   0.0  0.000000
30   0.0   0.0  0.000000   0.0  0.053942  ...   0.0   0.0   0.0   0.0  0.023944
31   0.0   0.0  0.000000   0.0  0.048718  ...   0.0   0.0   0.0   0.0  0.002591

[32 rows x 4096 columns]